### ISSUE TITLE
Multipart form data file upload runs into size limit issue

### ISSUE THREAD

**Issue by girishbr** [swagger-api/swagger-node#338]
I have this file upload api (multipart/form-data) and I run into a http 413 when I upload a 3.2 mb json file.
```
{
  "expected": 3207276,
  "length": 3207276,
  "limit": 102400,
  "status": 413,
  "statusCode": 413,
  "message": "request entity too large",
  "type": "entity.too.large"
}
```
Swagger-node uses multer internally. And multer doesn't really impose any restrictions. https://github.com/expressjs/multer#limits

and neither do you, in swagger tools, https://github.com/apigee-127/swagger-tools/blob/master/middleware/swagger-metadata.js#L41, impose any limits.

I run express 4, so body parser is ruled out.

I am running on localhost, no nginx or any other proxy in between.

**Comment by ramden** [comment]
+1

**Comment by girishbr** [comment]
@ramden downgrade to express 3. Everything works like a charm! Weird though.

**Comment by NickBlow** [comment]
+1 any solutions so far?

**Comment by NickBlow** [comment]
I got it working by injecting my own version of multer, in case anyone has the same issue and wants to stick with express 4. Just have a look at the multer docs for whatever settings you want to use, this is the code I used that stores files up to 52mb in memory and has a single file being uploaded called 'file'. 

```
import SwaggerExpress from 'swagger-express-mw';
import express from 'express';
import multer from 'multer';
...
let app = express();

SwaggerExpress.create(config, (err, swaggerExpress) => {
  if (err) {
    throw err;
  }
  let storage = multer.memoryStorage(); //you might need to change this, check multer docs

  let mult = multer({ //you might need to change this, check multer docs
    storage: storage,
    limits: {
      fileSize: 52428800
    }
  }).fields([{name: "file"}]);

  app.use(mult);

  // install middleware
  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  app.listen(port);
});

```

**Comment by Boelensman1** [comment]
+1 The above solution does for some reason not work for me.

Am trying to find out why the default setup does not work in express 4

**Comment by johnmurphy01** [comment]
+1 Any updates on this? I'm running into the same problem. @NickBlow's solution isn't working at the moment but am still trying to figure it out.

**Comment by wompeter** [comment]
+1

**Comment by johnmurphy01** [comment]
I had to add the following yaml file to my project:
```
# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    swagger_params_parser:
      name: swagger_params_parser
      jsonOptions:
        limit: '5mb'

    # pipe for all swagger-node controllers
    swagger_controllers:
      - cors
      - swagger_security
      - swagger_params_parser
      - _swagger_validate
      - express_compatibility
      - _router
    
    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
```
Pay attention particularly to the `jsonOptions` setting. 

I created a swagger folder in my project and underneath I had my default.yaml file with the above and my swagger.json file with my definitions. I then removed bodyParser because I was still using it but it was not needed since swagger handles it for you.
