### ISSUE TITLE
use mock.js to solve static mock data

### ISSUE THREAD

**Issue by longzhiyou** [swagger-api/swagger-node#384]
### use [mock.js]( https://github.com/nuysoft/Mock/wiki/Mock.Random)
in  swagger-router.js  getMockValue function
### these was my changed files
``` javascript

var Mock = require('../lib/mock');


var getMockValue = function (version, schema) {
  var type = _.isPlainObject(schema) ? schema.type : schema;
  var xmock =_.isPlainObject(schema) ? schema['x-mock'] : schema;
  var Random = Mock.Random;

  var value;
  var temp;
  
  
  if(xmock){
	var data = xmock.split("|");
    type =data[0];
    if(data.length>1)
        temp = data[1];
  }
  if (!type) {
    type = 'object';

  }

  switch (type) {

  //x-type
  case 'url':
    value = Random.url();
    break;
  case 'date':
    value = Random.date(temp);
    break;

  case 'array':
      // 默认三个数组
    value = [getMockValue(version, _.isArray(schema.items) ? schema.items[0] : schema.items),
      getMockValue(version, _.isArray(schema.items) ? schema.items[0] : schema.items),
      getMockValue(version, _.isArray(schema.items) ? schema.items[0] : schema.items)
    ];



    break;

  case 'boolean':
    if (version === '1.2' && !_.isUndefined(schema.defaultValue)) {
      value = schema.defaultValue;
    } else if (version === '2.0' && !_.isUndefined(schema.default)) {
      value = schema.default;
    } else if (_.isArray(schema.enum)) {
      value = schema.enum[0];
    } else {
      value = 'true';
    }

    // Convert value if necessary
    value = value === 'true' || value === true ? true : false;

    break;

  case 'file':
  case 'File':
    value = 'Pretend this is some file content';

    break;

  case 'integer':
    if (version === '1.2' && !_.isUndefined(schema.defaultValue)) {
      value = schema.defaultValue;
    } else if (version === '2.0' && !_.isUndefined(schema.default)) {
      value = schema.default;
    } else if (_.isArray(schema.enum)) {
      value = schema.enum[0];
    } else {
      var Random = Mock.Random
      value = Random.integer(1,1000)||1;
    }

    // Convert value if necessary
    if (!_.isNumber(value)) {
      value = parseInt(value, 10);
    }

    // TODO: Handle constraints and formats

    break;

  case 'object':
    value = {};

    _.each(schema.allOf, function (parentSchema) {
      _.each(parentSchema.properties, function (property, propName) {
        value[propName] = getMockValue(version, property);
      });
    });

    _.each(schema.properties, function (property, propName) {
      value[propName] = getMockValue(version, property);
    });

    break;

  case 'number':
    if (version === '1.2' && !_.isUndefined(schema.defaultValue)) {
      value = schema.defaultValue;
    } else if (version === '2.0' && !_.isUndefined(schema.default)) {
      value = schema.default;
    } else if (_.isArray(schema.enum)) {
      value = schema.enum[0];
    } else {
      // value = 1.0;

      value = Random.url();

    }

    // Convert value if necessary
    if (!_.isNumber(value)) {
      value = parseFloat(value);
    }

    // TODO: Handle constraints and formats

    break;

  case 'string':
    if (version === '1.2' && !_.isUndefined(schema.defaultValue)) {
      value = schema.defaultValue;
    } else if (version === '2.0' && !_.isUndefined(schema.default)) {
      value = schema.default;
    } else if (_.isArray(schema.enum)) {
      value = schema.enum[0];
    } else {
      if (schema.format === 'date') {
        value = new Date().toISOString().split('T')[0];
      } else if (schema.format === 'date-time') {
        value = new Date().toISOString();

      } else {
        // var Random = Mock.Random
        value = Random.name();
        // value = 'Sample text';
      }
    }

    break;

  }

  return value;
};

```
### you can custom mock type like 'x-mock: date' in swagger.yaml
``` yaml
definitions:
  Product:
    type: object
    properties:
      product_id:
        type: string
        description: Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
      description:
        type: string
        description: Description of product.
      display_name:
        type: string
        description: Display name of product.
      capacity:
        type: string
       x-mock: date
        description: Capacity of product. For example, 4 people.
      image:
        type: string
        description: Image URL representing the product.
```
