### ISSUE TITLE
dot in url path returns 404

### ISSUE THREAD

**Issue by AliUz** [swagger-api/swagger-node#420]
swagger.yaml file: 
```yaml
/users/{userId}:
    x-swagger-router-controller: users
    get:
      description: Returns a user by the given id
      operationId: show
      parameters:
        - name: userId
          in: path
          description: a id of a user to fetch
          required: true
          type: string
```

If i send the following request I get a 404: `/users/john.smith/`

Is there a way to escape the dot?

Thanks!
