### ISSUE TITLE
How to validate api_key(s) ?

### ISSUE THREAD

**Issue by PedroEsperanca** [swagger-api/swagger-node#425]
I've been looking for a solution for a while now, I might be missing some important documentation or maybe it should be added to the project's README.md

**Comment by k00p** [comment]
I followed [this solution](http://stackoverflow.com/questions/31974579/how-should-i-handle-an-application-javascript-response-type-in-swagger) from stack overflow and it worked for me. It required a major refactor though!

**Comment by tanzim** [comment]
@k00p not sure why it has to be complex and you should NOT certainly be using swagger tools for this! Swagger (via swagger node runner[1]) supports having security definition as a fitting.

I don't have an example lying around for API keys, but here's a basic auth example which should be similar to API key as the principle is the same:

- Create `security-handler.js` in `api/swagger` folder.   
For reference, this is how it might look like:

```javascript
'use strict';

const debug = require('debug')('swagger:security');
const _ = require('lodash');
const basicauth = require('basic-auth');

function BasicAuth(req, res, next) {
  debug('BasicAuth');
  // Credentials returned by basic auth is actually a function (class)
  // the pod conversion is so that isEqual doesn't get confused
  const credentials = _.toPlainObject(basicauth(req));
  if (_.isEqual(credentials, { name: 'foo', pass: 'bar' })) return next();
  debug('BasicAuth. invalid/incorrect credentials');
  return next(new Error()); // Use something like https://github.com/jshttp/http-errors in production to return error with status code
}

module.exports = {
  BasicAuth
};

```

- Add basic authentication in your swagger definition in `api/swagger/swagger.yaml` and :
```yaml
paths:
/accounts:
    x-swagger-router-controller: accounts-controller
    get:      
      operationId: getAccounts
      security:
        - BasicAuth: []
      parameters:
        - name: ...
# API security options
securityDefinitions:
  BasicAuth:
    type: basic
```

- Tell `swagger` where to find your security handler fitting. You do this by modifying the configuration files in `config/{environment|default}.yaml` [1]. For example:

```yaml
_swagger_security:
  name: swagger_security
  securityHandlersModule: api/swagger/security-handlers
```

- Instantiate swagger middleware normally in your server

```javascript
const SwaggerExpress = require('swagger-express-mw');
...
SwaggerExpress.create({ appRoot: __dirname }, (error, swagger) => {
  const app = express();
  swagger.register(app);
  ...
});

```

And that's all.

[1] https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.10
