### ISSUE TITLE
sway/parameter.js errors out

### ISSUE THREAD

**Issue by efog** [swagger-api/swagger-node#431]
I upgraded the project dependencies to version 0.7.0 and since then, for any of the endpoints defined with query parameters sway library throws this error: req.query must be provided for 'query' parameters. When using a path parameter, this error is thrown by sway: Cannot read property 'id' of undefined. One workaround is to use version 0.1.0 of the middleware runner.

**Comment by efog** [comment]
Changed default.yaml with this and it resolved the issue:

```yml
    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
```
