### ISSUE TITLE
swagger-hapi statusCode not returned properly

### ISSUE THREAD

**Issue by efog** [swagger-api/swagger-node#432]
From a project generated with the cli, it's not possible to return a proper status code. swagger-hapi is version 0.1.0. Here's the return code method used:

```javascript
   res.statusCode = 401;
  res.end(data);
```

All is gotten is statusCode 200 notwithstanding the status code passed.

**Comment by efog** [comment]
Changed default.yml with this and it fixed the issue:
```yml
    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
```
