### ISSUE TITLE
How to get parameter from POST body?

### ISSUE THREAD

**Issue by jbeuckm** [swagger-api/swagger-node#438]
To get YAML working in the editor, I had to put everything in a body parameter like this:
```
    parameters
        - name: body
          in: body
          required: true
          schema:
            properties:
              myParam:
                type: string

````
This implies that to access a post param in my controller, I have to do:

`req.swagger.params.body.value.myParam`

That is very cumbersome. Is that the only way to parse my POST body?
