### ISSUE TITLE
Swagger project is incompatible with future versions of 'swagger-express-mw'

### ISSUE THREAD

**Issue by Yohanna** [swagger-api/swagger-node#460]
Currently the Express project generated by Swagger uses version `0.1.0` of [`swagger-express-mw`](https://www.npmjs.com/package/swagger-express-mw), [See here](https://github.com/swagger-api/swagger-node/blob/master/project-skeletons/express/package.json).

However, `swagger-express-mw` was recently upgraded to v.[0.6.0](https://github.com/apigee-127/swagger-express/releases) which broke compatibility with Swagger-node.
Running the skeleton project after upgrading to v.`0.6.0` results in the property `params` in `req.swagger`
being undefined, so something like `req.swagger.params` will fail.

You might already know this, but just thought I'd open an issue to give other people a heads up.

**Comment by shashank734** [comment]
+1
also body parameter fails. INVALID_REQUEST_PARAMETER like this.

**Comment by jeffswitzer** [comment]
I ran into this too, but found a solution. When upgrading swagger-express-mw you need to modify your default.yaml file adding the line `- swagger_params_parser` under `swagger_controllers:` For example mine looks like this now:
```
    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
```
Look at the breaking changes section here: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0

**Comment by Yohanna** [comment]
@jeffswitzer Thanks! that fixed it.

**Comment by KwankiAhn** [comment]
@jeffswitzer THANKS!!! IT WORKS ON ME ALSO.

**Comment by leojh** [comment]
This fix still works, the boilerplate should have this change

**Comment by gjblanco-clutch** [comment]
under what are you adding swagger_controllers? the generated code (after swagger project create) does not include that key

**Comment by jeffswitzer** [comment]
@gjblanco-clutch here is an example of default.yaml under the config directory:

```
# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
```
