### ISSUE TITLE
Basic authorization - unknown security handler

### ISSUE THREAD

**Issue by ric79** [swagger-api/swagger-node#478]
Hello,
I'm totally new to swagger and I'm try to implement Basic Auth on my REST service.
In my swagger.yaml I added:

```
securityDefinitions:
 UserSecurity:
  type: apiKey
  name: Authorization
  in: header  
...
path:
 /login:
    post:
     parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/Login'
     responses:
       "200":
          schema:
            $ref: '#/definitions/Token'
 /users:
   x-swagger-router-controller: authentication
   get:
     security:
       - UserSecurity: []
```

When I use Swagger Editor I follow this way
1) I execute `login `and get the token
```
{
  "token": "a123"
}
```

2) I insert in the Authorization banner:
UserSecurity: a123

3) I execute `user` and I get this error:
```
Host: xxx.it
Accept: application/xml
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8,fa;q=0.6,sv;q=0.4
Cache-Control: no-cache
Connection: keep-alive
Origin: http://xxx.it:51643
Referer: http://xxx:51643/
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Authorization: UserSecurity: a123

{
  "message": "unknown security handler: UserSecurity",
  "code": "server_error",
  "statusCode": 403
}
```

What am I missing?
Riccardo

**Comment by davux** [comment]
Any information about how you resolved this? I'm having the same problem.

**Comment by ric79** [comment]
This is the solution that I've implemented...

**Comment by johnmarhefka** [comment]
Hi @ric79 , did you share anything? I've been banging my head on this issue today and I'm quite interested in the solution. :) Thanks!

**Comment by ric79** [comment]
Hello, no gist shared. However the post explains my solution

**Comment by ChristianRich** [comment]
+1

**Comment by benishak** [comment]
where is the fucking solution and post you are talking about ? @ric79

**Comment by webron** [comment]
@benishak I've deleted your post for obvious reasons. Please be respectful to others in the future.

**Comment by benishak** [comment]
Thanks and sorry
I didn't mean to be disrespectful to anybody, I was mentioning the post and not the person.

Anyway I think I solved this issue and I will share my solution here so everyone benefits.

**Comment by benishak** [comment]
I'm using the last version of `swagger-express-mw`

in *api/config/default.yaml* I had the following settings

```
# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    _swagger_params_parser:
      name: swagger_params_parser
      jsonOptions:
        type: "application/*+json"
      urlencodedOptions:
        extended: true
      multerOptions:
        inMemory: true
      textOptions:
        type: "*/*"

    _json_error_handler:
      name: json_error_handler
      handle500Errors: true

    _swagger_security:
      name: swagger_security
      securityHandlersModule: api/helpers/auth.mw

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: _json_error_handler
      - cors
      - _swagger_params_parser
      - _swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
```

in *api/helpers/auth.mw.js* I had the following

```
const passport = require('passport');
const app = require('../../app');
require('../../config/passport')(app, passport);

app.passport = passport;

module.exports = {};

module.exports.jwt = function (req, def, scopes, callback) {
    const $ = passport.authenticate('jwt', { session: false}, function(error, user, info) {
        if (error) {
            var err = new Error('Error in JWT authentication process');
            err.status = 500;
            return callback(err);
        }

        if (!user) {
          var err = new Error('Authentication failed,: ' + info);
          err.status = 401;
          return callback(err);
        }

        req.user = user;
        return callback();
    });

    $(req, null, callback);
}
```

and in *swagger.yaml* I have

```
securityDefinitions:
  jwt:
    type: apiKey
    name: apiKey
    in: query

security:
 - jwt: []
```
