### ISSUE TITLE
default value does not show up in req.swagger.params if using in: body

### ISSUE THREAD

**Issue by terencechow** [swagger-api/swagger-node#482]
This seems like a bug to me. Not sure if it is a bug in swagger-node or swagger-core.

Already raised a [stackoverflow question](http://stackoverflow.com/questions/42581052/where-does-default-value-show-up-in-swagger-node-request) with no results.

To reiterate that SO question:

given the below swagger definition:

```
/myroute:
    x-swagger-router-controller: myroute
    post:
        operationId: createSomething
        parameters:
            - name: payload
              in: body
              required: true
              schema:
                  type: object
                  properties:
                      somedefault:
                          type: string
                          default: teststring
```

I would expect `console.log(req.swagger.params.payload.value)` in my `createSomething` function to be:

`{somedefault: 'teststring'}`

Instead I get nothing showing for the key `somedefault`. 

Further, if you use `default` on a parameter that is `in: query` , the default value exists when console logging it. This tells me the issue may be specific to the `in: body`.
